import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, NavLink, Navigate, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { BedDouble, CalendarCheck, Home, LogOut, Sparkles, Users, ClipboardCheck } from 'lucide-react';
import { LineChart, Line, ResponsiveContainer, Tooltip, CartesianGrid, XAxis, YAxis } from 'recharts';
import { api } from './api/client';
import './styles.css';

const nav = [['/', Home, 'Dashboard'], ['/rooms', BedDouble, 'Rooms'], ['/bookings', CalendarCheck, 'Bookings'], ['/guests', Users, 'Guests'], ['/tasks', ClipboardCheck, 'Tasks']];
function Shell({ children }) { const navigate = useNavigate(); return <div className="shell"><aside><div className="brand"><Sparkles/> Luxe Hotel OS</div>{nav.map(([to,Icon,label])=><NavLink key={to} to={to} className={({isActive})=>isActive?'active':''}><Icon size={18}/>{label}</NavLink>)}<button className="ghost" onClick={()=>{localStorage.clear();navigate('/login')}}><LogOut size={18}/> Logout</button><p className="credits">Crafted with credits to <b>Chinmay</b> & <b>Krutick</b></p></aside><main>{children}</main></div> }
function Protected({ children }) { return localStorage.getItem('token') ? <Shell>{children}</Shell> : <Navigate to="/login"/>; }
function Login(){ const [email,setEmail]=useState('chinmay@luxeos.dev'),[password,setPassword]=useState('password123'),[err,setErr]=useState(''); const nav=useNavigate(); async function submit(e){e.preventDefault();setErr('');try{const {data}=await api.post('/auth/login',{email,password});localStorage.setItem('token',data.token);localStorage.setItem('user',JSON.stringify(data.user));nav('/')}catch{setErr('Invalid login. Try seed credentials.')}} return <div className="login"><motion.form initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} onSubmit={submit} className="loginCard"><span className="pill">Market-ready hotel management</span><h1>Luxe Hotel OS</h1><p>Animated full-stack command center for bookings, rooms, guests and operations.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button>Login</button>{err&&<small>{err}</small>}<div className="mini">Credits: Chinmay & Krutick</div></motion.form></div> }
function Card({children,i=0}){return <motion.div className="card" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:i*.06}}>{children}</motion.div>}
function Dashboard(){const [d,setD]=useState(null);useEffect(()=>{api.get('/dashboard').then(r=>setD(r.data))},[]); if(!d)return <h2>Loading dashboard…</h2>; const chart=[{m:'Jan',rev:42000},{m:'Feb',rev:62000},{m:'Mar',rev:83000},{m:'Apr',rev:d.stats.revenue},{m:'May',rev:98000}]; return <><Header title="Executive Dashboard" sub="Live hotel performance, arrivals and revenue intelligence."/><section className="grid stats">{Object.entries(d.stats).map(([k,v],i)=><Card key={k} i={i}><span>{k.replace(/([A-Z])/g,' $1')}</span><b>{k==='revenue'?`₹${v.toLocaleString()}`:v}</b></Card>)}</section><Card><h3>Revenue Pulse</h3><ResponsiveContainer width="100%" height={260}><LineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="m"/><YAxis/><Tooltip/><Line dataKey="rev" strokeWidth={3}/></LineChart></ResponsiveContainer></Card><section className="grid">{d.arrivals.map((b,i)=><Card key={b.id} i={i}><h3>{b.code}</h3><p>{b.guest.name} · Room {b.room.number}</p><span className="tag">{b.status}</span></Card>)}</section></>}
function Header({title,sub}){return <motion.div className="hero" initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}}><span className="pill">Luxe Operations Suite</span><h1>{title}</h1><p>{sub}</p></motion.div>}
function Rooms(){const [items,setItems]=useState([]);useEffect(()=>{api.get('/rooms').then(r=>setItems(r.data))},[]);return <><Header title="Room Inventory" sub="Room availability, pricing, capacity and amenities."/><section className="roomGrid">{items.map((r,i)=><Card key={r.id} i={i}><img src={r.image}/><div className="row"><h3>{r.type}</h3><span className="tag">{r.status}</span></div><p>Room {r.number} · Floor {r.floor} · {r.capacity} guests</p><b>₹{r.price.toLocaleString()}/night</b><small>{r.amenities}</small></Card>)}</section></>}
function Bookings(){const [items,setItems]=useState([]);useEffect(()=>{api.get('/bookings').then(r=>setItems(r.data))},[]);return <><Header title="Bookings" sub="Reservations, check-ins, check-outs and payments."/><Table rows={items.map(b=>[b.code,b.guest.name,b.room.number,b.status,`₹${b.totalAmount.toLocaleString()}`])} heads={['Code','Guest','Room','Status','Total']}/></>}
function Guests(){const [items,setItems]=useState([]);useEffect(()=>{api.get('/guests').then(r=>setItems(r.data))},[]);return <><Header title="Guest CRM" sub="Guest profiles, contact data and VIP flags."/><Table rows={items.map(g=>[g.name,g.email,g.phone,g.country,g.vip?'VIP':'Regular'])} heads={['Name','Email','Phone','Country','Tier']}/></>}
function Tasks(){const [items,setItems]=useState([]);useEffect(()=>{api.get('/tasks').then(r=>setItems(r.data))},[]);return <><Header title="Staff Tasks" sub="Housekeeping, maintenance and concierge operations."/><section className="grid">{items.map((t,i)=><Card key={t.id} i={i}><h3>{t.title}</h3><p>{t.area} · {new Date(t.dueAt).toLocaleString()}</p><span className="tag">{t.priority} · {t.status}</span></Card>)}</section></>}
function Table({heads,rows}){return <Card><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></Card>}
function App(){return <BrowserRouter><Routes><Route path="/login" element={<Login/>}/><Route path="/" element={<Protected><Dashboard/></Protected>}/><Route path="/rooms" element={<Protected><Rooms/></Protected>}/><Route path="/bookings" element={<Protected><Bookings/></Protected>}/><Route path="/guests" element={<Protected><Guests/></Protected>}/><Route path="/tasks" element={<Protected><Tasks/></Protected>}/></Routes></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);
